name: Azure_data_factory_deploy
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - UAT

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: UAT
          path: main
      - uses: actions/checkout@v2
        with:
          ref: adf_publish
          path: adf

      - name: Inspect GitHub workflows
        run: ls -la $GITHUB_WORKSPACE/
        shell: bash

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            [String] $path= $env:GITHUB_WORKSPACE
            Write-Host $path
            .\main\cicd.ps1 -armTemplate "$path/adf/git-dev-adf/ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.AZURE_RG }} -DataFactoryName "git-uat-adf" -predeployment $true -deleteDeployment $false
          azPSVersion: 3.1.0

      - name: Deploy ADF Artifacts
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file $GITHUB_WORKSPACE/adf/git-dev-adf/ARMTemplateForFactory.json --parameters @$GITHUB_WORKSPACE/adf/git-dev-adf/ARMTemplateForFactory.json --parameters factoryName="git-uat-adf" AzureBlobStorage1_connectionString="DefaultEndpointsProtocol=https;AccountName=storagenk2;AccountKey=bjjHhhKPsBJTmdTzCgXRGAA9grIG33Jqad5qEwBTwLcRo3db67Zx93tqkQ3qFejdWIWep64A4FTkNYfmyiWRDA==;EndpointSuffix=core.windows.net" AzureBlobStorage2_connectionString="DefaultEndpointsProtocol=https;AccountName=storagenk3;AccountKey=sayb2ruOacYHU5DbYrFjSR5urlqwPLeaVtYozIsvRknEks0mp9ANdLplD9n3rSm96Jgfebj80kOWLbjdBpsdfw==;EndpointSuffix=core.windows.net"

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            [String] $path= $env:GITHUB_WORKSPACE
            Write-Host $path
            .\main\cicd.ps1 -armTemplate "$path/adf/git-dev-adf/ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.AZURE_RG }} -DataFactoryName "git-uat-adf" -predeployment $true -deleteDeployment $true
          azPSVersion: 3.1.0
